# -*- coding: utf-8 -*-
# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License version 3, as published by
# the Free Software Foundation.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#

"""
Django settings for ominicontacto project.

Generated by 'django-admin startproject' using Django 1.9.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'configuracion_telefonia_app.apps.ConfiguracionTelefoniaAppConfig',
    'crispy_forms',
    'compressor',
    'defender',
    'formtools',
    'ominicontacto_app.apps.OminicontactoAppConfig',
    'reciclado_app.apps.RecicladoAppConfig',
    'reportes_app.apps.ReportesAppConfig',
    'supervision_app.apps.SupervisionAppConfig',
    'notification_app.apps.NotificationAppConfig',
    'notification_app.message.apps.Config',
    'simple_history',
    'widget_tweaks',
    'rest_framework',
    'rest_framework.authtoken',
    'api_app.apps.ApiAppConfig',
    'whatsapp_app.apps.WhatsappAppConfig',
    'orquestador_app.apps.OrquestadorAppConfig',
    'facebook_meta_app.apps.FacebookMetaAppConfig',
    'instagram_app.apps.InstagramAppConfig',
    'email_app.apps.AppConfig',
    'constance',
    'django_js_reverse',
    'import_export',
    'django_extensions',
    'constance.backends.database',
    'django_sass',
    'django_sendfile',
    'easyaudit'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'defender.middleware.FailedLoginMiddleware',
    'ominicontacto_app.middleware.permiso_oml.PermisoOMLMiddleware',
    'easyaudit.middleware.easyaudit.EasyAuditMiddleware',
]


# django-compressor settings
COMPRESS_OFFLINE = True

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # other finders..
    'compressor.finders.CompressorFinder',
)

ROOT_URLCONF = 'ominicontacto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [os.path.join(os.path.dirname(__file__),'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ominicontacto_app.context_processors.global_settings',
                'ominicontacto_app.context_processors.addon_menu_items',
            ],
        },
    },
    {
        "BACKEND": "django.template.backends.jinja2.Jinja2",
        "APP_DIRS": True,
        "OPTIONS": {
            "environment": "ominicontacto_app.template_backends_jinja2.environment",
            "keep_trailing_newline": False,
            "lstrip_blocks": True,
            "trim_blocks": True,
        }
    },
]

ASGI_APPLICATION = 'ominicontacto.asgi.application'
WSGI_APPLICATION = 'ominicontacto.wsgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Password hashers available
# https://docs.djangoproject.com/en/1.9/topics/auth/passwords/

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024 # 10 Mb limit

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 600
SESSION_SAVE_EVERY_REQUEST = True

DTMF_DURATION = 50  # Duración de cada tono en ms
DTMF_INTER_TONE_GAP = 100  # Intervalo entre tonos en ms

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

TIME_ZONE = 'America/Argentina/Cordoba'

USE_I18N = True



USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
OML_PUBLIC_MEDIA_BASE_URL = None
OML_SIGNED_MEDIA_URL_EXPIRE_SECONDS = 432000
WHATSAPP_WEBHOOK_STREAM_MAXLEN = 10000
ORCHESTRATOR_SLAVE_STREAM_FROMID = '$'

STATICFILES_DIRS = [
    ("omnileads-frontend", os.path.join(BASE_DIR, "omnileads_ui/dist")),
    ("webui-app", os.path.join(BASE_DIR, "webui/dist")),
]

# Nota Django 6: El valor por defecto de DEFAULT_AUTO_FIELD cambió a 'django.db.models.BigAutoField'
# Mantenemos 'AutoField' explícitamente para compatibilidad con migraciones existentes.
# Si decides cambiar a BigAutoField, necesitarás crear migraciones para actualizar los tipos de columna.
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
AUTH_USER_MODEL = 'ominicontacto_app.User'

TEST_RUNNER = "tests.tests.ManagedModelTestRunner"
OML_TESTING_MODE = False

LOGIN_REDIRECT_URL = 'index'

OL_SIP_LIMITE_INFERIOR = 1000
OL_SIP_LIMITE_SUPERIOR = 3000

OL_NRO_EXT_BPX_LARGO_MIN = 3
"""Largo minimo permitido de nros de extensiones BPX"""

OL_NRO_TELEFONO_LARGO_MIN = 5
"""Largo minimo permitido de nros telefonicos"""

OL_NRO_TELEFONO_LARGO_MAX = 15
"""Largo maximo permitido de nros telefonicos"""

OL_MAX_CANTIDAD_CONTACTOS = 60000
"""Límite de contactos que pueden ser importados a la base de datos."""

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

OML_DUMP_HTTP_AMI_RESPONSES = False

# ==============================================================================
# Settings de DEPLOY (para ser customizados en distintos deploys)
#     Nota: Los settings que siguen, pueden (y algunos DEBEN) ser modificados
#        en los distintos ambientes / deploys
# ==============================================================================

# ==============================================================================
# DEPLOY -> Asterisk
# ==============================================================================

OML_OMNILEADS_HOSTNAME = None
OML_ASTERISK_REMOTEPATH = None

# ==============================================================================
# DEPRECATED: Los siguientes settings están deprecados y ya no se utilizan.
# Se mantienen únicamente por compatibilidad hacia atrás con despliegues
# antiguos. Estos archivos de configuración ya no se generan ni se envían
# a través del stream Redis `asterisk_conf_updater`:
# - `oml_pjsip_agents.conf` (endpoints SIP de agentes)
# - `oml_queues.conf` (colas)
# - `oml_extensions_outr.conf` (rutas salientes)
#
# La funcionalidad de agentes SIP, colas y rutas salientes ahora se maneja
# mediante otros mecanismos (Kamailio, ARI/ACD, dialer).
# ==============================================================================
OML_SIP_FILENAME = None
OML_QUEUES_FILENAME = None
OML_RUTAS_SALIENTES_FILENAME = None
"""DEPRECATED: Path completo (absoluto) al archivo donde se generaba queues.

Este setting está deprecado y ya no se utiliza. Los archivos `oml_pjsip_agents.conf`,
`oml_queues.conf` y `oml_extensions_outr.conf` ya no se generan ni se distribuyen.

Se mantiene únicamente por compatibilidad hacia atrás.

Ejemplos históricos (ya no aplican):

.. code-block:: python

    OML_ASTERISK_REMOTEPATH = "/etc/asterisk/"
    OML_SIP_FILENAME = "/etc/asterisk/sip_fts.conf"
    OML_QUEUES_FILENAME = "/etc/asterisk/queues_fts.conf"  # DEPRECATED
    OML_RUTAS_SALIENTES_FILENAME = "/etc/asterisk/oml_extensions_outr.conf"  # DEPRECATED
"""

ASTERISK = {
    'AMI_USERNAME': None,  # Usuario para AMI
    'AMI_PASSWORD': None,  # Password para usuario para AMI
    # URL usado por Daemon p/acceder a Asterisk AMI via HTTP
    # Ej:
    #    "http://1.2.3.4:7088"
}


DJANGO_DEBUG_TOOLBAR = None

######################
# Defender variables #
######################

DEFENDER_BEHIND_REVERSE_PROXY = None
# Variable obligatoria, se tiene que saber que el defender está detras de un proxy

#######################################
# Ephemeral SIP credentials variables #
#######################################

SIP_SECRET_KEY = None
# Secret key usada para SIP credentials

EPHEMERAL_USER_TTL = None
# Tiempo de duración de credenciales efimeras

OML_KAMAILIO_HOSTNAME = None
# Hostname para conectarse a Kamailio

"""Comando para obtener el secret_key de kamailio y asi poder generar la SIP password

Ejemplo:

    OML_KAMAILIO_CMD = \
        "kamcmd -s /opt/omnileads/kamailio/run/kamailio/kamailio_ctl autheph.dump_secrets"

"""

TMPL_OML_AUDIO_CONVERSOR = None
"""Comando para convertir audios (wav a gsm)

Ejemplos:

.. code-block:: python

    TMPL_OML_AUDIO_CONVERSOR = ["sox", "<INPUT_FILE>", "<OUTPUT_FILE>"]

Para transformar WAV (cualquier formato) -> WAV (compatible con Asterisk):

.. code-block:: python

    TMPL_OML_AUDIO_CONVERSOR = ["sox", "-t", "wav", "<INPUT_FILE>",
        "-r", "8k", "-c", "1", "-e", "signed-integer",
        "-t", "wav", "<OUTPUT_FILE>"
    ]

"""

TMPL_OML_AUDIO_CONVERSOR_EXTENSION = None
"""Extension a usar para archivo generado por `TMPL_OML_AUDIO_CONVERSOR`

Ejemplo: `.wav` (con el . incluido):  el archivo `<OUTPUT_FILE>`
tendra la extension `.wav`
"""

OML_AUDIO_PATH_ASTERISK = None
"""Directory donde se guardan los audios de asterisk en el server de asterisk

Ejemplo:
    OML_WOMBAT_FILENAME = "/var/lib/asterisk/sounds/oml/"
"""

OML_PLAYLIST_PATH_ASTERISK = None
"""Directory donde se guardan las playlist de music on hold en el server de asterisk

Ejemplo:
    OML_PLAYLIST_PATH_ASTERISK = '/var/lib/asterisk/sounds/oml/moh/'
"""

# ==============================================================================
# WOMBAT Config
# ==============================================================================

OML_WOMBAT_URL = None
"""Url de discador de Wombat

Ejemplo:
    OML_WOMBAT_URL = "http://172.16.20.222/wombat"
"""


OML_WOMBAT_FILENAME = None
"""Directory donde se guardan los json de config de wombat

Ejemplo:
    OML_WOMBAT_FILENAME = "/home/freetech/"
"""

OML_WOMBAT_USER = None
OML_WOMBAT_PASSWORD = None
OML_WOMBAT_TIMEOUT = None
"""
User y password por el cual se conectan con la api de WOMBAT DIALER
Ejemplo:
    OML_WOMBAT_USER = "user_test"
    OML_WOMBAT_PASSWORD = "user123"
OML_WOMBAT_TIMEOUT es el tiempo de timeout de la request hacia Wombat API
"""

CALIFICACION_REAGENDA = None

# configuración de Django Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'api_app/locale'),
    os.path.join(BASE_DIR, 'configuracion_telefonia_app/locale'),
    os.path.join(BASE_DIR, 'email_app/locale'),
    os.path.join(BASE_DIR, 'notification_app/locale'),
    os.path.join(BASE_DIR, 'ominicontacto_app/locale'),
    os.path.join(BASE_DIR, 'reportes_app/locale'),
    os.path.join(BASE_DIR, 'reciclado_app/locale'),
    os.path.join(BASE_DIR, 'supervision_app/locale'),
    os.path.join(BASE_DIR, 'whatsapp_app/locale'),
    os.path.join(BASE_DIR, 'instagram_app/locale'),
)

LANGUAGES = (
    ('pt-br', 'Portuguese-Br'),
    ('en', 'English'),
    ('es', 'Spanish'),
    ('fa', 'Persian'),
)

LANGUAGE_CODE = 'es'

TOKEN_EXPIRED_AFTER_SECONDS = None

VERLOOP_DISPOSITION_OPTION_ID = None
"""ID de la opción de calificación (disposition option) a usar para las
dispositions creadas desde el webhook de Verloop.

Esta configuración debe establecerse mediante la variable de entorno
VERLOOP_DISPOSITION_OPTION_ID o en el archivo de settings local.

Ejemplo:
    VERLOOP_DISPOSITION_OPTION_ID = 32
"""

VERLOOP_CALIFICACION_NOMBRE = 'GESTION_BOT'
"""Nombre de la OpcionCalificacion que el webhook de Verloop interpreta como
"fin de gestión del voicebot". Cuando la calificación aplicada al contacto
coincide con este valor (y el request trae call_id), la vista publica el
comando voicebot_transfer_proceed en Redis para que el ACD continúe la
transferencia que quedó pendiente tras el REFER del bot."""

VERLOOP_BOT_AGENT_USERNAME = None
"""Username del AgenteProfile a asociar a las calificaciones creadas por el
webhook de Verloop cuando el usuario autenticado no es un agente.

Si no se define o el username no corresponde a un agente activo, se cae al
comportamiento anterior: primer agente de la campaña → primer agente activo
del sistema."""

VERLOOP_DEBUG_PAYLOAD = False
"""Cuando es True, el webhook de Verloop emite logs INFO con el body JSON
completo recibido y los headers (Authorization enmascarado). Útil para
troubleshooting puntual; dejar en False en producción para evitar volcar
información sensible y/o ruidosa en los logs.

Se puede activar desde el entorno con la variable VERLOOP_DEBUG_PAYLOAD=True."""

VOICEBOT_CALIFICACION_NOMBRE = 'GESTION_BOT'
"""Nombre de la OpcionCalificacion que el webhook genérico de voicebot interpreta como
"fin de gestión del voicebot". Cuando la calificación aplicada al contacto
coincide con este valor (y el request trae call_id), la vista publica el
comando voicebot_transfer_proceed en Redis para que el ACD continúe la
transferencia que quedó pendiente tras el REFER del bot."""

VOICEBOT_BOT_AGENT_USERNAME = None
"""Username del AgenteProfile a asociar a las calificaciones creadas por el
webhook genérico de voicebot cuando el usuario autenticado no es un agente.

Si no se define o el username no corresponde a un agente activo, se cae al
comportamiento anterior: primer agente de la campaña → primer agente activo
del sistema."""

VOICEBOT_DEBUG_PAYLOAD = False
"""Cuando es True, el webhook genérico de voicebot emite logs INFO con el body JSON
completo recibido y los headers (Authorization enmascarado). Útil para
troubleshooting puntual; dejar en False en producción para evitar volcar
información sensible y/o ruidosa en los logs.

Se puede activar desde el entorno con la variable VOICEBOT_DEBUG_PAYLOAD=True."""

ALLOW_FEEDBACK = False

CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

DJANGO_EASY_AUDIT_REGISTERED_CLASSES = [
    'ominicontacto_app.campana',
    'ominicontacto_app.queue',
    'ominicontacto_app.agenteprofile'
]

DJANGO_EASY_AUDIT_REGISTERED_URLS = [
    r'^/reporte/llamadas/',
    r'^/reportes/agentes_tiempos/',
    r'^/auditar_gestion/buscar/(\d+)/',
    r'^/campana/(\d+)/reporte_grafico/',
    r'^/reporte_de_resultados/(\d+)/',
    r'^/campana/(\d+)/reporte_calificacion/',
    r'^/premium_reports/',
    r'^/grabacion/buscar/(\d+)/',
]

DJANGO_EASY_AUDIT_REMOTE_ADDR_HEADER = 'HTTP_X_REAL_IP'

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

X_FRAME_OPTIONS = 'SAMEORIGIN'

def _env_int(name, default):
    val = os.getenv(name)
    if val is None or val == '':
        return default
    try:
        return int(val)
    except ValueError:
        return default


# Presence log: cooldown en ms para idempotencia de SESSION_LOGIN.
# Si hay LOGOUT y dentro de esta ventana se intenta LOGIN, se considera reconexión
# y no se persiste otro SESSION_LOGIN (evita flapping login/logout/login).
# Ejemplo: 1000 = 1 segundo. Configurable por entorno.
PRESENCE_LOG_RECONNECT_COOLDOWN_MS = _env_int('PRESENCE_LOG_RECONNECT_COOLDOWN_MS', 1500)

# Presence heartbeat (console browser -> Redis/V2).
PRESENCE_HEARTBEAT_INTERVAL_SEC = _env_int('PRESENCE_HEARTBEAT_INTERVAL_SEC', 15)
PRESENCE_HEARTBEAT_TIMEOUT_SEC = _env_int('PRESENCE_HEARTBEAT_TIMEOUT_SEC', 60)
PRESENCE_HEARTBEAT_SWEEP_SEC = _env_int('PRESENCE_HEARTBEAT_SWEEP_SEC', 15)
PRESENCE_HEARTBEAT_LOGOUT_RECENT_SEC = _env_int('PRESENCE_HEARTBEAT_LOGOUT_RECENT_SEC', 90)
PRESENCE_HEARTBEAT_GUARD_TTL_SEC = _env_int('PRESENCE_HEARTBEAT_GUARD_TTL_SEC', 90)
