# Generated by Django 3.2.19 on 2026-08-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_meta_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginametafacebook',
            name='app_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionmetafacebookcampana',
            name='pagina',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name='campanas', to='facebook_meta_app.paginametafacebook'),
        ),
    ]
