# Generated by Django 3.2.19 on 2026-05-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0117_canalidad_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='email_habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contacto',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='grupo',
            name='email_habilitado',
            field=models.BooleanField(default=False, verbose_name='Permiso de uso de la canalidad Email'),
        ),
    ]
