# Generated by Django 3.2.19 on 2026-06-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0117_canalidad_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='pause_on_first_login',
            field=models.BooleanField(default=False, verbose_name='Pausar al iniciar sesión'),
        ),
    ]
