# Generated by Codex on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0118_grupo_pause_on_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='instagram_habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contacto',
            name='ig_scoped_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='grupo',
            name='instagram_habilitado',
            field=models.BooleanField(
                default=False,
                verbose_name='Permiso de uso de la canalidad Instagram',
            ),
        ),
        migrations.AlterField(
            model_name='calificacioncliente',
            name='canalidad',
            field=models.PositiveIntegerField(
                choices=[
                    (0, 'Teléfono'),
                    (1, 'Whatsapp'),
                    (2, 'Facebook'),
                    (3, 'Instagram'),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name='historicalcalificacioncliente',
            name='canalidad',
            field=models.PositiveIntegerField(
                choices=[
                    (0, 'Teléfono'),
                    (1, 'Whatsapp'),
                    (2, 'Facebook'),
                    (3, 'Instagram'),
                ],
                default=0,
            ),
        ),
    ]
