# Unique identifier of the project in SonarQube
sonar.projectKey=omnileads-django

# Name of the project
sonar.projectName=OMniLeads Django

# Path to the source directories
sonar.sources=.

# Exclude third-party libraries, migrations, static assets, and tests from source analysis
sonar.exclusions=**/migrations/**, **/static/vendor/**, **/node_modules/**, **/bower_components/**, **/tests/**, **/test/**, **/staticfiles/**, **/venv/**

# Path to test files
sonar.tests=.
sonar.test.inclusions=**/tests/**, **/test/**, test_*.py, *_test.py

# Encoding of the source files
sonar.sourceEncoding=UTF-8
