# -*- coding: utf-8 -*-
# Copyright (C) 2018 Freetech Solutions
#
# This file is part of OMniLeads
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License version 3, as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#

from django.db import migrations, models
from django.db.models import deletion


def create_resumen_transfer_tables(apps, schema_editor):
    """
    Crea las tablas reportes_app_llamada_resumen y reportes_app_transferlog
    con todos sus campos e índices.
    """
    with schema_editor.connection.cursor() as cursor:
        # 1. Crear tabla reportes_app_llamada_resumen
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS public.reportes_app_llamada_resumen (
                id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                callid                      varchar(64) NOT NULL,
                campana_id                  integer,
                tipo_campana                integer,
                tipo_llamada                integer,
                agente_id                   integer,
                contacto_id                 integer,
                numero_marcado              varchar(128),
                fecha_inicio                timestamptz,
                fecha_fin                   timestamptz,
                duracion_segundos           numeric(10,3),
                bridge_wait_time            numeric(10,3),
                event                       varchar(32),
                archivo_grabacion           varchar(256),
                es_transferencia            boolean NOT NULL DEFAULT false,
                calificacion_id             integer,
                opcion_calificacion_id      integer,
                opcion_calificacion_nombre  varchar(100),
                opcion_calificacion_tipo    integer,
                subcalificacion             varchar(200),
                es_venta                    boolean NOT NULL DEFAULT false,
                created_at                  timestamptz NOT NULL DEFAULT now(),
                updated_at                  timestamptz NOT NULL DEFAULT now(),
                atendida_por_voicebot       boolean NOT NULL DEFAULT false,
                atencion_hibrida            boolean NOT NULL DEFAULT false,
                canalidad                   varchar(16) CHECK (canalidad IN ('TEL', 'EMAIL', 'WA', 'FBMSN', 'IGDI', 'SMS')),
                node_id                     varchar(64),
                tenant_id                   varchar(64),
                hangup_trigger              varchar(16) CHECK (hangup_trigger IS NULL OR hangup_trigger IN ('AGENT', 'EXTERNAL', 'OTHER')),

                CONSTRAINT reportes_app_llamada_resumen_callid_key UNIQUE (callid)
            );
        """)

        # 2. Crear índices para reportes_app_llamada_resumen
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_resumen_callid
            ON public.reportes_app_llamada_resumen (callid);
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_resumen_agente_fecha
            ON public.reportes_app_llamada_resumen (agente_id, fecha_fin);
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_resumen_calificacion
            ON public.reportes_app_llamada_resumen (calificacion_id);
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_resumen_campana_fecha
            ON public.reportes_app_llamada_resumen (campana_id, fecha_fin);
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_resumen_fecha_fin
            ON public.reportes_app_llamada_resumen (fecha_fin);
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_resumen_hibrida_fecha
            ON public.reportes_app_llamada_resumen (atencion_hibrida, fecha_fin);
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_resumen_venta_fecha
            ON public.reportes_app_llamada_resumen (es_venta, fecha_fin);
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_resumen_voicebot_fecha
            ON public.reportes_app_llamada_resumen (atendida_por_voicebot, fecha_fin);
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_resumen_node_id
            ON public.reportes_app_llamada_resumen (node_id);
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_resumen_tenant_id
            ON public.reportes_app_llamada_resumen (tenant_id);
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_resumen_hangup_trigger
            ON public.reportes_app_llamada_resumen (hangup_trigger);
        """)

        # 3. Crear tabla reportes_app_transferlog
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS public.reportes_app_transferlog (
                id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at          timestamptz NOT NULL DEFAULT now(),
                callid              varchar(64) NOT NULL,
                leg_unique_id       varchar(64),
                contacto_id         integer,
                campana_id_origen   integer,
                agente_origen_id    integer,
                initiated_by        varchar(16) NOT NULL DEFAULT 'AGENTE',
                transfer_type       varchar(16) NOT NULL,
                numero_extra        varchar(64),
                target_agent_id     integer,
                target_campaign_id  integer,
                new_leg_unique_id   varchar(64),
                resultado           varchar(32) DEFAULT 'INIT',
                sip_code            integer,
                sip_reason          varchar(64),
                duration_ms         integer,
                talk_time           integer
            );
        """)

        # 4. Crear índices para reportes_app_transferlog
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_transferlog_callid
            ON public.reportes_app_transferlog (callid);
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_transferlog_created_at
            ON public.reportes_app_transferlog (created_at);
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_transferlog_agente
            ON public.reportes_app_transferlog (agente_origen_id);
        """)


def reverse_resumen_transfer_tables(apps, schema_editor):
    """
    Elimina las tablas creadas en la migración.
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS public.reportes_app_transferlog CASCADE;")
        cursor.execute("DROP TABLE IF EXISTS public.reportes_app_llamada_resumen CASCADE;")


def create_interactions_tables(apps, schema_editor):
    """
    Crea las tablas de interacciones omnicanal:
    - interactions_summary (resumen y KPIs, con wait_conn_duration)
    - interaction_journey (trazabilidad paso a paso)
    - interaction_transfers (transferencias vinculadas al journey)
    """
    with schema_editor.connection.cursor() as cursor:
        # 1. Tabla maestra de interacciones (wait_conn_duration desde el inicio)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS public.interactions_summary (
                id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                interaction_id          VARCHAR(64) NOT NULL UNIQUE,
                tenant_id               VARCHAR(64) NOT NULL,
                node_id                 VARCHAR(64),
                campaign_id             INTEGER,
                channel_type            VARCHAR(16) NOT NULL,
                direction               VARCHAR(16) NOT NULL DEFAULT 'INBOUND',
                initiation_method       VARCHAR(32),
                status                  VARCHAR(32) NOT NULL,
                hangup_cause            VARCHAR(32),
                source_address          VARCHAR(256),
                destination_address     VARCHAR(256),
                start_time              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                end_time                TIMESTAMPTZ,
                total_duration          NUMERIC(10,3) DEFAULT 0,
                bot_duration            NUMERIC(10,3) DEFAULT 0,
                wait_conn_duration      NUMERIC(10,3) DEFAULT 0,
                agent_duration          NUMERIC(10,3) DEFAULT 0,
                agent_id                INTEGER,
                disposition_id          INTEGER,
                customer_id             INTEGER,
                outcome                 BOOLEAN DEFAULT FALSE,
                is_transferred          BOOLEAN DEFAULT FALSE,
                transfer_count          INTEGER DEFAULT 0,
                channel_data            JSONB DEFAULT '{}'::jsonb,
                created_at              TIMESTAMPTZ DEFAULT NOW(),
                updated_at              TIMESTAMPTZ DEFAULT NOW(),
                CONSTRAINT check_direction CHECK (direction IN ('INBOUND', 'OUTBOUND')),
                CONSTRAINT interactions_summary_initiation_method_valid
                    CHECK (initiation_method IS NULL OR initiation_method IN ('AGENT', 'DIALER', 'BOT'))
            );
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_summ_date
            ON public.interactions_summary (start_time);
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_summ_tenant_node
            ON public.interactions_summary (tenant_id, node_id);
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_summ_inter_id
            ON public.interactions_summary (interaction_id);
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_summ_metadata
            ON public.interactions_summary USING gin (channel_data);
        """)

        # 2. Tabla de customer journey
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS public.interaction_journey (
                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                interaction_id      VARCHAR(64) NOT NULL,
                sequence_number     INTEGER NOT NULL,
                node_type           VARCHAR(32) NOT NULL,
                node_name           VARCHAR(128),
                action              VARCHAR(32),
                payload             JSONB DEFAULT '{}'::jsonb,
                timestamp           TIMESTAMPTZ DEFAULT NOW()
            );
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_journey_interaction_seq
            ON public.interaction_journey (interaction_id, sequence_number);
        """)

        # 3. Tabla de transferencias (FK a interaction_journey)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS public.interaction_transfers (
                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                interaction_id      VARCHAR(64) NOT NULL,
                journey_entry_id    BIGINT REFERENCES public.interaction_journey(id) ON DELETE SET NULL,
                source_agent_id     INTEGER,
                source_channel      VARCHAR(128),
                destination_target  VARCHAR(128) NOT NULL,
                destination_type    VARCHAR(32),
                transfer_type       VARCHAR(20),
                status              VARCHAR(20),
                fail_reason         VARCHAR(64),
                created_at          TIMESTAMPTZ DEFAULT NOW(),
                completed_at        TIMESTAMPTZ,
                talk_time_after     NUMERIC(10,3) DEFAULT 0
            );
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_transfers_int_id
            ON public.interaction_transfers (interaction_id);
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_transfers_journey_link
            ON public.interaction_transfers (journey_entry_id);
        """)


def reverse_interactions_tables(apps, schema_editor):
    """
    Elimina las tablas en orden inverso (por la FK interaction_transfers -> interaction_journey).
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS public.interaction_transfers CASCADE;")
        cursor.execute("DROP TABLE IF EXISTS public.interaction_journey CASCADE;")
        cursor.execute("DROP TABLE IF EXISTS public.interactions_summary CASCADE;")


class Migration(migrations.Migration):

    dependencies = [
        ('reportes_app', '0011_analisissentimiento'),
        ('ominicontacto_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_resumen_transfer_tables,
            reverse_resumen_transfer_tables,
        ),
        migrations.RunPython(
            create_interactions_tables,
            reverse_interactions_tables,
        ),
        migrations.CreateModel(
            name='AgentActivityEventV2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(db_index=True)),
                ('agente_id', models.IntegerField(db_index=True)),
                ('event_type', models.CharField(
                    choices=[
                        ('SESSION_LOGIN', 'SESSION_LOGIN'),
                        ('SESSION_LOGOUT', 'SESSION_LOGOUT'),
                        ('STATE_READY', 'STATE_READY'),
                        ('STATE_PAUSED', 'STATE_PAUSED'),
                        ('STATE_ACW', 'STATE_ACW'),
                    ],
                    max_length=32,
                )),
                ('pause', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=deletion.SET_NULL,
                    to='ominicontacto_app.pausa',
                )),
                ('aux_code', models.CharField(blank=True, max_length=32, null=True)),
                ('source', models.CharField(blank=True, max_length=16, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reportes_app_agentactivityeventv2',
            },
        ),
        migrations.AddIndex(
            model_name='agentactivityeventv2',
            index=models.Index(fields=['agente_id', '-ts'], name='reports_aae2_agente_ts'),
        ),
        migrations.AddIndex(
            model_name='agentactivityeventv2',
            index=models.Index(fields=['-ts'], name='reports_aae2_ts_desc'),
        ),
        migrations.AddIndex(
            model_name='agentactivityeventv2',
            index=models.Index(fields=['event_type'], name='reports_aae2_event_type'),
        ),
    ]
