# Generated by Django 3.2.19 on 2025-12-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes_app', '0011_analisissentimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, db_index=True)),
                ('callid', models.CharField(max_length=32, unique=True)),
                ('transcription_status', models.SmallIntegerField(choices=[(0, 'Vacío'), (1, 'Procesando'), (2, 'Finalizado'), (3, 'Error')], default=0)),
                ('transcription_file', models.CharField(blank=True, max_length=100, null=True)),
                ('sentiment_status', models.SmallIntegerField(choices=[(0, 'Vacío'), (1, 'Procesando'), (2, 'Finalizado'), (3, 'Error')], default=0)),
                ('sentiment_file', models.CharField(blank=True, max_length=100, null=True)),
                ('qa_status', models.SmallIntegerField(choices=[(0, 'Vacío'), (1, 'Procesando'), (2, 'Finalizado'), (3, 'Error')], default=0)),
                ('qa_file', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
