# Generated by Codex on 2026-05-29

import django.db.models.deletion
import django.utils.timezone
import instagram_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion_telefonia_app', '0026_instagram_destinoentrante_tipo'),
        ('ominicontacto_app', '0119_canalidad_instagram'),
        ('facebook_meta_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaInstagram',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.IntegerField(choices=[(0, 'Texto')])),
                ('configuracion', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoPlantillaInstagram',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('plantillas', models.ManyToManyField(
                    related_name='grupos', to='instagram_app.PlantillaInstagram')),
            ],
            options={
                'verbose_name': 'Grupo de Plantillas de Instagram',
                'verbose_name_plural': 'Grupos de Plantillas de Instagram',
            },
        ),
        migrations.CreateModel(
            name='CuentaInstagram',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('access_token', models.CharField(max_length=500)),
                ('verify_token', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=255)),
                ('page_id', models.CharField(max_length=255)),
                ('ig_user_id', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('validated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                    related_name='instagram_accounts',
                    to='configuracion_telefonia_app.destinoentrante')),
                ('goodbye_message', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                    related_name='accounts_goodbye_message',
                    to='instagram_app.plantillainstagram')),
                ('horario', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                    related_name='instagram_accounts',
                    to='configuracion_telefonia_app.grupohorario')),
                ('out_of_hours_message', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                    related_name='accounts_out_of_hours_message',
                    to='instagram_app.plantillainstagram')),
                ('welcome_message', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                    related_name='accounts_welcome_message',
                    to='instagram_app.plantillainstagram')),
            ],
            options={
                'verbose_name': 'Instagram Account Configuration',
                'verbose_name_plural': 'Instagram Account Configurations',
            },
        ),
        migrations.CreateModel(
            name='ConversationInstagramApp',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_scoped_id', models.CharField(max_length=255, null=True)),
                ('is_disposition', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expire', models.DateTimeField(null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('atendida', models.BooleanField(default=False)),
                ('error', models.BooleanField(default=False)),
                ('error_ex', models.JSONField(default=dict)),
                ('date_last_interaction', models.DateTimeField(null=True)),
                ('client_alias', models.CharField(max_length=100, null=True)),
                ('account', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='conversations_instagram',
                    to='instagram_app.cuentainstagram')),
                ('agent', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE,
                    related_name='conversations_instagram',
                    to='ominicontacto_app.agenteprofile')),
                ('campana', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                    related_name='instagram_conversaciones',
                    to='ominicontacto_app.campana')),
                ('client', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE,
                    related_name='conversations_instagram',
                    to='ominicontacto_app.contacto')),
                ('conversation_disposition', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE,
                    related_name='conversations_instagram',
                    to='ominicontacto_app.historicalcalificacioncliente')),
            ],
            options={
                'verbose_name': 'Instagram App Conversation',
                'verbose_name_plural': 'Instagram App Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageInstagramApp',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('origen', models.CharField(max_length=100)),
                ('sender', models.JSONField(default=dict)),
                ('content', models.JSONField(default=dict)),
                ('type', models.CharField(max_length=100)),
                ('file', models.FileField(
                    blank=True, max_length=1000, null=True,
                    upload_to=instagram_app.models.upload_to)),
                ('status', models.CharField(max_length=100)),
                ('fail_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('conversation', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE,
                    related_name='messages',
                    to='instagram_app.conversationinstagramapp')),
            ],
            options={
                'verbose_name': 'Instagram App Message',
                'verbose_name_plural': 'Instagram App Messages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='conversationinstagramapp',
            name='last_message',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='+', to='instagram_app.messageinstagramapp'),
        ),
        migrations.CreateModel(
            name='AttachmentInstagramApp',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='attachments',
                    to='instagram_app.messageinstagramapp')),
            ],
            options={
                'verbose_name': 'Instagram App Attachment',
                'verbose_name_plural': 'Instagram App Attachments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MenuInteractivoInstagram',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_header', models.CharField(max_length=1024)),
                ('texto_opcion_incorrecta', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('texto_derivacion', models.CharField(max_length=100)),
                ('timeout', models.IntegerField(null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('account', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                    related_name='menuinteractivo',
                    to='instagram_app.cuentainstagram')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionMenuInteractivoInstagram',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=72)),
                ('opcion', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='opcion_menu_instagram_app',
                    to='configuracion_telefonia_app.opciondestino')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionInstagramCampana',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_servicio', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('campana', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='configuracion_instagram',
                    to='ominicontacto_app.campana')),
                ('cuenta', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='campanas',
                    to='instagram_app.cuentainstagram')),
                ('grupo_plantilla_instagram', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                    related_name='configuracion_instagram',
                    to='instagram_app.grupoplantillainstagram')),
                ('grupo_plantilla_facebook', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                    related_name='configuracion_instagram',
                    to='facebook_meta_app.grupoplantillamessenger')),
            ],
            options={
                'verbose_name': 'Configuración Instagram Campaña',
                'verbose_name_plural': 'Configuraciones Instagram Campaña',
            },
        ),
    ]
