# Generated by Django 3.2.19 on 2026-06-19 16:06

import django.contrib.postgres.fields
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import email_app.models._utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ominicontacto_app', '0118_auto_20260506_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('settings', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('insights', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_bytes', models.BinaryField()),
                ('content_stamp', models.CharField(max_length=64)),
                ('mailbox_uidva', models.CharField(max_length=100)),
                ('date', models.DateTimeField(null=True)),
                ('subject', email_app.models._utils.TruncatedCharField(max_length=254)),
                ('from_mail', models.CharField(max_length=254)),
                ('from_name', models.CharField(max_length=100)),
                ('to_mail', models.CharField(max_length=254)),
                ('to_name', models.CharField(max_length=100)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField()),
                ('message_id', models.CharField(max_length=254)),
                ('in_reply_to', models.CharField(max_length=254)),
                ('references', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=254), default=list, size=None)),
                ('attachments', models.JSONField(default=list)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='email_app.account')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_level', models.IntegerField(default=90)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_accounts', to='email_app.account')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='email_account', to='ominicontacto_app.campana')),
            ],
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['content_stamp'], name='email_app-content_stamp-idx'),
        ),
    ]
