/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IHugeiconsAdd01: typeof import('~icons/hugeicons/add01')['default']
    IHugeiconsAlert01: typeof import('~icons/hugeicons/alert01')['default']
    IHugeiconsAlert02: typeof import('~icons/hugeicons/alert02')['default']
    IHugeiconsAlertCircle: typeof import('~icons/hugeicons/alert-circle')['default']
    IHugeiconsArrowLeft01: typeof import('~icons/hugeicons/arrow-left01')['default']
    IHugeiconsAttachment01: typeof import('~icons/hugeicons/attachment01')['default']
    IHugeiconsCheckmarkSquare02: typeof import('~icons/hugeicons/checkmark-square02')['default']
    IHugeiconsDatabaseSync: typeof import('~icons/hugeicons/database-sync')['default']
    IHugeiconsDelete02: typeof import('~icons/hugeicons/delete02')['default']
    IHugeiconsHelpCircle: typeof import('~icons/hugeicons/help-circle')['default']
    IHugeiconsHome02: typeof import('~icons/hugeicons/home02')['default']
    IHugeiconsMail01: typeof import('~icons/hugeicons/mail01')['default']
    IHugeiconsMailAtSign01: typeof import('~icons/hugeicons/mail-at-sign01')['default']
    IHugeiconsMessageMultiple01: typeof import('~icons/hugeicons/message-multiple01')['default']
    IHugeiconsMicroscope: typeof import('~icons/hugeicons/microscope')['default']
    IHugeiconsMinusSignSquare: typeof import('~icons/hugeicons/minus-sign-square')['default']
    IHugeiconsPencilEdit02: typeof import('~icons/hugeicons/pencil-edit02')['default']
    IHugeiconsRefreshDot: typeof import('~icons/hugeicons/refresh-dot')['default']
    IHugeiconsRepost: typeof import('~icons/hugeicons/repost')['default']
    IHugeiconsSave: typeof import('~icons/hugeicons/save')['default']
    IHugeiconsSaveAll: typeof import('~icons/hugeicons/save-all')['default']
    IHugeiconsSettingDone04: typeof import('~icons/hugeicons/setting-done04')['default']
    IHugeiconsSettingError04: typeof import('~icons/hugeicons/setting-error04')['default']
    IHugeiconsSettings03: typeof import('~icons/hugeicons/settings03')['default']
    IHugeiconsSquare: typeof import('~icons/hugeicons/square')['default']
    ISvgSpinnersBarsScale: typeof import('~icons/svg-spinners/bars-scale')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkelSkin: typeof import('./src/components/skel-skin.vue')['default']
    ViewportBreakpoint: typeof import('./src/components/viewport-breakpoint.vue')['default']
  }
}

// For TSX support
declare global {
  const IHugeiconsAdd01: typeof import('~icons/hugeicons/add01')['default']
  const IHugeiconsAlert01: typeof import('~icons/hugeicons/alert01')['default']
  const IHugeiconsAlert02: typeof import('~icons/hugeicons/alert02')['default']
  const IHugeiconsAlertCircle: typeof import('~icons/hugeicons/alert-circle')['default']
  const IHugeiconsArrowLeft01: typeof import('~icons/hugeicons/arrow-left01')['default']
  const IHugeiconsAttachment01: typeof import('~icons/hugeicons/attachment01')['default']
  const IHugeiconsCheckmarkSquare02: typeof import('~icons/hugeicons/checkmark-square02')['default']
  const IHugeiconsDatabaseSync: typeof import('~icons/hugeicons/database-sync')['default']
  const IHugeiconsDelete02: typeof import('~icons/hugeicons/delete02')['default']
  const IHugeiconsHelpCircle: typeof import('~icons/hugeicons/help-circle')['default']
  const IHugeiconsHome02: typeof import('~icons/hugeicons/home02')['default']
  const IHugeiconsMail01: typeof import('~icons/hugeicons/mail01')['default']
  const IHugeiconsMailAtSign01: typeof import('~icons/hugeicons/mail-at-sign01')['default']
  const IHugeiconsMessageMultiple01: typeof import('~icons/hugeicons/message-multiple01')['default']
  const IHugeiconsMicroscope: typeof import('~icons/hugeicons/microscope')['default']
  const IHugeiconsMinusSignSquare: typeof import('~icons/hugeicons/minus-sign-square')['default']
  const IHugeiconsPencilEdit02: typeof import('~icons/hugeicons/pencil-edit02')['default']
  const IHugeiconsRefreshDot: typeof import('~icons/hugeicons/refresh-dot')['default']
  const IHugeiconsRepost: typeof import('~icons/hugeicons/repost')['default']
  const IHugeiconsSave: typeof import('~icons/hugeicons/save')['default']
  const IHugeiconsSaveAll: typeof import('~icons/hugeicons/save-all')['default']
  const IHugeiconsSettingDone04: typeof import('~icons/hugeicons/setting-done04')['default']
  const IHugeiconsSettingError04: typeof import('~icons/hugeicons/setting-error04')['default']
  const IHugeiconsSettings03: typeof import('~icons/hugeicons/settings03')['default']
  const IHugeiconsSquare: typeof import('~icons/hugeicons/square')['default']
  const ISvgSpinnersBarsScale: typeof import('~icons/svg-spinners/bars-scale')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SkelSkin: typeof import('./src/components/skel-skin.vue')['default']
  const ViewportBreakpoint: typeof import('./src/components/viewport-breakpoint.vue')['default']
}