# -*- coding: utf-8 -*-
# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License version 3, as published by
# the Free Software Foundation.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
from django.urls import path

from . import consumers

websocket_urlpatterns = [
    path('channels/agent-console', consumers.AgentConsole.as_asgi()),
    path('channels/agent-console-whatsapp', consumers.AgentConsoleWhatsapp.as_asgi()),
    path('channels/agent-console-email', consumers.AgentConsoleEmail.as_asgi()),
    path('channels/supervisor', consumers.DialerStatsConsumer.as_asgi(), name='c0'),
    path('channels/omnidialer', consumers.DialerStatsConsumer.as_asgi(), name='c1'),
    path('channels/omnidialer/<secret>', consumers.DialerStatsConsumer.as_asgi(), name='c2'),
    path('channels/supervision/<section>', consumers.SupervisionConsumer.as_asgi(),
         name='supervision'),
    path('channels/reporte_centro_contacto_canalidades/<str:task_id>',
         consumers.ReporteCentroContactoCanalidadesCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_canalidades_csv'),
    path('channels/reporte_centro_contacto_canalidades_egresos/<str:task_id>',
         consumers.ReporteCentroContactoCanalidadesEgresosCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_canalidades_egresos_csv'),
    path('/channels/reporte_centro_contacto_canalidades_egresos/<str:task_id>',
         consumers.ReporteCentroContactoCanalidadesEgresosCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_canalidades_egresos_csv_slash'),
    path('channels/reporte_centro_contacto_canalidades_por_hora/<str:task_id>',
         consumers.ReporteCentroContactoCanalidadesPorHoraCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_canalidades_por_hora_csv'),
    path('channels/reporte_centro_contacto_canalidades_por_hora_egresos/<str:task_id>',
         consumers.ReporteCentroContactoCanalidadesPorHoraEgresosCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_canalidades_por_hora_egresos_csv'),
    path('channels/reporte_centro_contacto_canalidades_por_dia/<str:task_id>',
         consumers.ReporteCentroContactoCanalidadesPorDiaCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_canalidades_por_dia_csv'),
    path('channels/reporte_centro_contacto_canalidades_por_dia_egresos/<str:task_id>',
         consumers.ReporteCentroContactoCanalidadesPorDiaEgresosCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_canalidades_por_dia_egresos_csv'),
    path('channels/reporte_centro_contacto_canalidades_por_mes/<str:task_id>',
         consumers.ReporteCentroContactoCanalidadesPorMesCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_canalidades_por_mes_csv'),
    path('channels/reporte_centro_contacto_canalidades_por_mes_egresos/<str:task_id>',
         consumers.ReporteCentroContactoCanalidadesPorMesEgresosCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_canalidades_por_mes_egresos_csv'),
    path('channels/reporte_centro_contacto_llamadas_atendidas_csv/<str:task_id>',
         consumers.ReporteCentroContactoLlamadasAtendidasCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_llamadas_atendidas_csv'),
    path('channels/reporte_centro_contacto_llamadas_atendidas_egresos_csv/<str:task_id>',
         consumers.ReporteCentroContactoLlamadasAtendidasEgresosCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_llamadas_atendidas_egresos_csv'),
    path('channels/reporte_centro_contacto_llamadas_no_atendidas_csv/<str:task_id>',
         consumers.ReporteCentroContactoLlamadasNoAtendidasCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_llamadas_no_atendidas_csv'),
    path('channels/reporte_centro_contacto_llamadas_no_atendidas_egresos_csv/<str:task_id>',
         consumers.ReporteCentroContactoLlamadasNoAtendidasEgresosCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_llamadas_no_atendidas_egresos_csv'),
    path('channels/reporte_centro_contacto_llamadas_voz/<str:task_id>',
         consumers.ReporteCentroContactoLlamadasVozCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_llamadas_voz_csv'),
    path('channels/reporte_centro_contacto_llamadas_voz_egresos/<str:task_id>',
         consumers.ReporteCentroContactoLlamadasVozEgresosCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_llamadas_voz_egresos_csv'),
    path('channels/reporte_centro_contacto_llamadas_por_hora/<str:task_id>',
         consumers.ReporteCentroContactoLlamadasPorHoraCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_llamadas_por_hora_csv'),
    path('channels/reporte_centro_contacto_llamadas_por_hora_egresos/<str:task_id>',
         consumers.ReporteCentroContactoLlamadasPorHoraEgresosCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_llamadas_por_hora_egresos_csv'),
    # Ruta con y sin barra inicial por diferencias en scope["path"] según proxy/ASGI
    path('channels/reporte_centro_contacto_llamadas_por_dia/<str:task_id>',
         consumers.ReporteCentroContactoLlamadasPorDiaCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_llamadas_por_dia_csv'),
    path('/channels/reporte_centro_contacto_llamadas_por_dia/<str:task_id>',
         consumers.ReporteCentroContactoLlamadasPorDiaCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_llamadas_por_dia_csv_slash'),
    path('channels/reporte_centro_contacto_llamadas_por_dia_egresos/<str:task_id>',
         consumers.ReporteCentroContactoLlamadasPorDiaEgresosCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_llamadas_por_dia_egresos_csv'),
    path('channels/reporte_centro_contacto_llamadas_por_mes/<str:task_id>',
         consumers.ReporteCentroContactoLlamadasPorMesCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_llamadas_por_mes_csv'),
    path('channels/reporte_centro_contacto_llamadas_por_mes_egresos/<str:task_id>',
         consumers.ReporteCentroContactoLlamadasPorMesEgresosCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_llamadas_por_mes_egresos_csv'),
    path('channels/reporte_centro_contacto_conversaciones_respondidas/<str:task_id>',
         consumers.ReporteCentroContactoConversacionesRespondidasCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_conversaciones_respondidas_csv'),
    path('channels/reporte_centro_contacto_conversaciones_respondidas_egresos/<str:task_id>',
         consumers.ReporteCentroContactoConversacionesRespondidasEgresosCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_conversaciones_respondidas_egresos_csv'),
    path('channels/reporte_centro_contacto_conversaciones_no_respondidas/<str:task_id>',
         consumers.ReporteCentroContactoConversacionesNoRespondidasCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_conversaciones_no_respondidas_csv'),
    path('channels/reporte_centro_contacto_conversaciones_no_respondidas_egresos/<str:task_id>',
         consumers.ReporteCentroContactoConversacionesNoRespondidasEgresosCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_conversaciones_no_respondidas_egresos_csv'),
    path('channels/reporte_centro_contacto_whatsapp_mensajes_por_hora_egresos/<str:task_id>',
         consumers.ReporteCentroContactoWhatsappMensajesPorHoraEgresosCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_whatsapp_mensajes_por_hora_egresos_csv'),
    path('channels/reporte_centro_contacto_whatsapp_mensajes_por_campana/<str:task_id>',
         consumers.ReporteCentroContactoWhatsappMensajesPorCampanaCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_whatsapp_mensajes_por_campana_csv'),
    path('channels/reporte_centro_contacto_whatsapp_mensajes_por_campana_egresos/<str:task_id>',
         consumers.ReporteCentroContactoWhatsappMensajesPorCampanaEgresosCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_whatsapp_mensajes_por_campana_egresos_csv'),
    path('channels/reporte_centro_contacto_whatsapp_mensajes_por_dia/<str:task_id>',
         consumers.ReporteCentroContactoWhatsappMensajesPorDiaCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_whatsapp_mensajes_por_dia_csv'),
    path('channels/reporte_centro_contacto_whatsapp_mensajes_por_dia_egresos/<str:task_id>',
         consumers.ReporteCentroContactoWhatsappMensajesPorDiaEgresosCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_whatsapp_mensajes_por_dia_egresos_csv'),
    path('channels/reporte_centro_contacto_whatsapp_mensajes_por_mes/<str:task_id>',
         consumers.ReporteCentroContactoWhatsappMensajesPorMesCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_whatsapp_mensajes_por_mes_csv'),
    path('channels/reporte_centro_contacto_whatsapp_mensajes_por_mes_egresos/<str:task_id>',
         consumers.ReporteCentroContactoWhatsappMensajesPorMesEgresosCSVConsumer.as_asgi(),
         name='reporte_centro_contacto_whatsapp_mensajes_por_mes_egresos_csv'),
    path('consumers/reporte_grafico_campana/agents_activity_listado/cc/<str:task_id>',
         consumers.ReporteAgentsActivityListadoCSVConsumer.as_asgi(),
         name='reporte_agents_activity_listado_csv'),
    path('consumers/reporte_grafico_campana/interacciones_por_agente/<str:campana_id>/<str:task_id>',
         consumers.ReporteInteraccionesPorAgenteCSVConsumer.as_asgi(),
         name='reporte_interacciones_por_agente_csv'),
    path('consumers/reporte_grafico_campana/performance_agentes/<str:campana_id>/<str:task_id>',
         consumers.ReportePerformanceAgentesCSVConsumer.as_asgi(),
         name='reporte_performance_agentes_csv'),
]
